namespace JobSearchSiteBackend.Core.Domains.Jobs.UseCases.GetDailyApplicationsForJobForDateRange;

public record GetDailyApplicationsForJobForDateRangeResult(List<Dictionary<DateTime, long>> DailyApplications);