using JobSearchSiteBackend.Core.Domains.Companies.Dtos;

namespace JobSearchSiteBackend.Core.Domains.Companies.UseCases.GetCompanyEmployeeInvitation;

public record GetCompanyEmployeeInvitationResult(CompanyEmployeeInvitationDto CompanyEmployeeInvitationDto);