using Core.Domains.JobContractTypes.Dtos;

namespace Core.Domains.JobContractTypes.UseCases.GetJobContractTypesByCountryId;

public record GetJobContractTypesByCountryIdResponse(ICollection<JobContractTypeIdWithName> JobContractTypeIdsWithNames);