using JobSearchSiteBackend.Core.Domains.Companies.Dtos;

namespace JobSearchSiteBackend.Core.Domains.Companies.UseCases.GetCompanyLastVisitedFolders;

public record GetCompanyLastVisitedFoldersResult(ICollection<CompanyJobFolderListItemDto> JobFolders);