// <auto-generated />
using System;
using JobSearchSiteBackend.Core.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobSearchSiteBackend.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MainDataContext))]
    partial class MainDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompanyUserProfile", b =>
                {
                    b.Property<long>("CompaniesWhereEmployedId")
                        .HasColumnType("bigint");

                    b.Property<long>("EmployeesId")
                        .HasColumnType("bigint");

                    b.HasKey("CompaniesWhereEmployedId", "EmployeesId");

                    b.HasIndex("EmployeesId");

                    b.ToTable("CompanyUserProfile");
                });

            modelBuilder.Entity("EmploymentOptionJob", b =>
                {
                    b.Property<long>("EmploymentOptionsId")
                        .HasColumnType("bigint");

                    b.Property<long>("JobsId")
                        .HasColumnType("bigint");

                    b.HasKey("EmploymentOptionsId", "JobsId");

                    b.HasIndex("JobsId");

                    b.ToTable("EmploymentOptionJob");
                });

            modelBuilder.Entity("JobApplicationPersonalFile", b =>
                {
                    b.Property<long>("JobApplicationsId")
                        .HasColumnType("bigint");

                    b.Property<long>("PersonalFilesId")
                        .HasColumnType("bigint");

                    b.HasKey("JobApplicationsId", "PersonalFilesId");

                    b.HasIndex("PersonalFilesId");

                    b.ToTable("JobApplicationPersonalFile");
                });

            modelBuilder.Entity("JobJobContractType", b =>
                {
                    b.Property<long>("JobContractTypesId")
                        .HasColumnType("bigint");

                    b.Property<long>("JobsId")
                        .HasColumnType("bigint");

                    b.HasKey("JobContractTypesId", "JobsId");

                    b.HasIndex("JobsId");

                    b.ToTable("JobJobContractType");
                });

            modelBuilder.Entity("JobLocation", b =>
                {
                    b.Property<long>("JobsId")
                        .HasColumnType("bigint");

                    b.Property<long>("LocationsId")
                        .HasColumnType("bigint");

                    b.HasKey("JobsId", "LocationsId");

                    b.HasIndex("LocationsId");

                    b.ToTable("JobLocation");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.Accounts.MyIdentityRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.Accounts.MyIdentityUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.Categories.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("NamePl")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("NamePl")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            NamePl = "Administracja biurowa"
                        },
                        new
                        {
                            Id = 2L,
                            NamePl = "Administracja publiczna / Służba cywilna"
                        },
                        new
                        {
                            Id = 3L,
                            NamePl = "Architektura"
                        },
                        new
                        {
                            Id = 4L,
                            NamePl = "Badania i rozwój"
                        },
                        new
                        {
                            Id = 5L,
                            NamePl = "Budownictwo / Geodezja"
                        },
                        new
                        {
                            Id = 6L,
                            NamePl = "Doradztwo / Konsulting"
                        },
                        new
                        {
                            Id = 7L,
                            NamePl = "Edukacja / Nauka / Szkolenia"
                        },
                        new
                        {
                            Id = 8L,
                            NamePl = "Energetyka / Elektronika"
                        },
                        new
                        {
                            Id = 9L,
                            NamePl = "Farmaceutyka / Biotechnologia"
                        },
                        new
                        {
                            Id = 10L,
                            NamePl = "Finanse / Bankowość"
                        },
                        new
                        {
                            Id = 11L,
                            NamePl = "Gastronomia / Catering"
                        },
                        new
                        {
                            Id = 12L,
                            NamePl = "Grafika / Fotografia / Kreacja"
                        },
                        new
                        {
                            Id = 13L,
                            NamePl = "Human Resources / Kadry"
                        },
                        new
                        {
                            Id = 14L,
                            NamePl = "Informatyka / Administracja"
                        },
                        new
                        {
                            Id = 15L,
                            NamePl = "Informatyka / Programowanie"
                        },
                        new
                        {
                            Id = 16L,
                            NamePl = "Internet / e-commerce"
                        },
                        new
                        {
                            Id = 17L,
                            NamePl = "Inżynieria / Projektowanie"
                        },
                        new
                        {
                            Id = 18L,
                            NamePl = "Kadra zarządzająca"
                        },
                        new
                        {
                            Id = 19L,
                            NamePl = "Kontrola jakości"
                        },
                        new
                        {
                            Id = 20L,
                            NamePl = "Kosmetyka / Pielęgnacja"
                        },
                        new
                        {
                            Id = 21L,
                            NamePl = "Księgowość / Audyt / Podatki"
                        },
                        new
                        {
                            Id = 22L,
                            NamePl = "Logistyka / Dystrybucja"
                        },
                        new
                        {
                            Id = 23L,
                            NamePl = "Marketing / Reklama / PR"
                        },
                        new
                        {
                            Id = 24L,
                            NamePl = "Media / Sztuka / Rozrywka"
                        },
                        new
                        {
                            Id = 25L,
                            NamePl = "Medycyna / Opieka zdrowotna"
                        },
                        new
                        {
                            Id = 26L,
                            NamePl = "Motoryzacja"
                        },
                        new
                        {
                            Id = 27L,
                            NamePl = "Nieruchomości"
                        },
                        new
                        {
                            Id = 28L,
                            NamePl = "Ochrona osób i mienia"
                        },
                        new
                        {
                            Id = 29L,
                            NamePl = "Organizacje pozarządowe / Wolontariat"
                        },
                        new
                        {
                            Id = 30L,
                            NamePl = "Praca fizyczna"
                        },
                        new
                        {
                            Id = 31L,
                            NamePl = "Praktyki / Staż"
                        },
                        new
                        {
                            Id = 32L,
                            NamePl = "Prawo"
                        },
                        new
                        {
                            Id = 33L,
                            NamePl = "Przemysł / Produkcja"
                        },
                        new
                        {
                            Id = 34L,
                            NamePl = "Rolnictwo / Ochrona środowiska"
                        },
                        new
                        {
                            Id = 35L,
                            NamePl = "Serwis / Technika / Montaż"
                        },
                        new
                        {
                            Id = 36L,
                            NamePl = "Sport / Rekreacja"
                        },
                        new
                        {
                            Id = 37L,
                            NamePl = "Sprzedaż / Obsługa klienta"
                        },
                        new
                        {
                            Id = 38L,
                            NamePl = "Telekomunikacja"
                        },
                        new
                        {
                            Id = 39L,
                            NamePl = "Tłumaczenia"
                        },
                        new
                        {
                            Id = 40L,
                            NamePl = "Transport / Spedycja"
                        },
                        new
                        {
                            Id = 41L,
                            NamePl = "Turystyka / Hotelarstwo"
                        },
                        new
                        {
                            Id = 42L,
                            NamePl = "Ubezpieczenia"
                        },
                        new
                        {
                            Id = 43L,
                            NamePl = "Zakupy"
                        },
                        new
                        {
                            Id = 44L,
                            NamePl = "Franczyza"
                        });
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.Companies.Company", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<string>("CountrySpecificFieldsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateTimeSyncedWithSearchUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimeUpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.Companies.CompanyAvatar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateTimeUpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GuidIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUploadedSuccessfully")
                        .HasColumnType("bit");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("GuidIdentifier")
                        .IsUnique();

                    b.ToTable("CompanyAvatars");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.Companies.CompanyBalanceTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<long>("CurrencyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateTimeCommittedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GuidIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("UserProfileId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("GuidIdentifier")
                        .IsUnique();

                    b.HasIndex("UserProfileId");

                    b.ToTable("CompanyBalanceTransactions");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.Companies.CompanyEmployeeInvitation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateTimeCreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GuidIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("InvitedUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("bit");

                    b.Property<long>("SenderUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("GuidIdentifier")
                        .IsUnique();

                    b.HasIndex("InvitedUserId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("CompanyEmployeeInvitations");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.CompanyClaims.CompanyClaim", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CompanyClaims");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "IsOwner"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "IsAdmin"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "CanReadStats"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "CanEditProfile"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "CanManageBalance"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "CanEditJobs"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "CanReadJobs"
                        },
                        new
                        {
                            Id = 8L,
                            Name = "CanManageApplications"
                        });
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.CompanyClaims.UserCompanyClaim", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClaimId")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCompanyClaims");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.Countries.Country", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "POL"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "DEU"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "FRA"
                        });
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.Countries.CountryCurrency", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<long>("CurrencyId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("CurrencyId");

                    b.ToTable("CountryCurrencies");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CountryId = 1L,
                            CurrencyId = 1L
                        });
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.Countries.Currency", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "PLN"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "EUR"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "USD"
                        });
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.EmploymentOptions.EmploymentOption", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("EmploymentOptionType")
                        .HasColumnType("int");

                    b.Property<string>("NamePl")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("NamePl")
                        .IsUnique();

                    b.ToTable("EmploymentOption");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            EmploymentOptionType = 2,
                            NamePl = "Pełny etat"
                        },
                        new
                        {
                            Id = 2L,
                            EmploymentOptionType = 2,
                            NamePl = "Część etatu"
                        },
                        new
                        {
                            Id = 3L,
                            EmploymentOptionType = 1,
                            NamePl = "W biurze"
                        },
                        new
                        {
                            Id = 4L,
                            EmploymentOptionType = 1,
                            NamePl = "Zdalnie"
                        },
                        new
                        {
                            Id = 5L,
                            EmploymentOptionType = 1,
                            NamePl = "Hybrydowo"
                        },
                        new
                        {
                            Id = 6L,
                            EmploymentOptionType = 1,
                            NamePl = "Z wyjazdami"
                        });
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.JobApplications.JobApplication", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateTimeCreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint");

                    b.Property<long>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("LocationId");

                    b.HasIndex("UserId");

                    b.ToTable("JobApplications");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.JobApplications.JobApplicationTag", b =>
                {
                    b.Property<long>("JobApplicationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("JobApplicationId", "Tag");

                    b.ToTable("JobApplicationTag");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.JobContractTypes.JobContractType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<string>("NamePl")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId", "NamePl")
                        .IsUnique();

                    b.ToTable("ContractTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CountryId = 1L,
                            NamePl = "Umowa o pracę"
                        },
                        new
                        {
                            Id = 2L,
                            CountryId = 1L,
                            NamePl = "Umowa o dzieło"
                        },
                        new
                        {
                            Id = 3L,
                            CountryId = 1L,
                            NamePl = "Umowa zlecenie"
                        },
                        new
                        {
                            Id = 4L,
                            CountryId = 1L,
                            NamePl = "Kontrakt B2B"
                        },
                        new
                        {
                            Id = 5L,
                            CountryId = 1L,
                            NamePl = "Umowa o pracę tymczasową"
                        },
                        new
                        {
                            Id = 6L,
                            CountryId = 1L,
                            NamePl = "Umowa agencyjna"
                        },
                        new
                        {
                            Id = 7L,
                            CountryId = 1L,
                            NamePl = "Umowa o staż/praktykę"
                        },
                        new
                        {
                            Id = 8L,
                            CountryId = 1L,
                            NamePl = "Umowa na zastępstwo"
                        });
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.Jobs.Job", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateTimeExpiringUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimePublishedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateTimeSyncedWithSearchUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimeUpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MaxDateTimeExpiringUtcEverSet")
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("NiceToHaves")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Requirements")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Responsibilities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.Jobs.JobPublicationInterval", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CountryCurrencyId")
                        .HasColumnType("bigint");

                    b.Property<int>("MaxDaysOfPublication")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CountryCurrencyId");

                    b.ToTable("JobPublicationIntervals");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CountryCurrencyId = 1L,
                            MaxDaysOfPublication = 5,
                            Price = 35m
                        },
                        new
                        {
                            Id = 2L,
                            CountryCurrencyId = 1L,
                            MaxDaysOfPublication = 30,
                            Price = 60m
                        },
                        new
                        {
                            Id = 3L,
                            CountryCurrencyId = 1L,
                            MaxDaysOfPublication = 60,
                            Price = 90m
                        },
                        new
                        {
                            Id = 4L,
                            CountryCurrencyId = 1L,
                            MaxDaysOfPublication = 90,
                            Price = 120m
                        });
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.Jobs.JobSalaryInfo", b =>
                {
                    b.Property<long>("JobId")
                        .HasColumnType("bigint");

                    b.Property<long>("CurrencyId")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsAfterTaxes")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Maximum")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("Minimum")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("UnitOfTime")
                        .HasColumnType("int");

                    b.HasKey("JobId");

                    b.ToTable("JobSalaryInfos");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.Locations.Location", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint");

                    b.Property<string>("DescriptionPl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsConcrete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.Locations.LocationRelation", b =>
                {
                    b.Property<long>("AncestorId")
                        .HasColumnType("bigint");

                    b.Property<long>("DescendantId")
                        .HasColumnType("bigint");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.HasKey("AncestorId", "DescendantId");

                    b.HasIndex("DescendantId");

                    b.ToTable("LocationRelations");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.PersonalFiles.PersonalFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DateTimeSyncedWithSearchUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimeUpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<Guid>("GuidIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUploadedSuccessfully")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PersonalFiles");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.UserProfiles.UserAvatar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateTimeUpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GuidIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUploadedSuccessfully")
                        .HasColumnType("bit");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("GuidIdentifier")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserAvatars");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.UserProfiles.UserJobApplicationBookmark", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateTimeCreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("JobApplicationId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("JobApplicationId");

                    b.HasIndex("UserId", "JobApplicationId")
                        .IsUnique();

                    b.ToTable("UserJobApplicationBookmarks");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.UserProfiles.UserJobBookmark", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateTimeCreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("UserId", "JobId")
                        .IsUnique();

                    b.ToTable("UserJobBookmarks");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.UserProfiles.UserProfile", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsReceivingApplicationStatusUpdates")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CompanyUserProfile", b =>
                {
                    b.HasOne("JobSearchSiteBackend.Core.Domains.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompaniesWhereEmployedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobSearchSiteBackend.Core.Domains.UserProfiles.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("EmployeesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmploymentOptionJob", b =>
                {
                    b.HasOne("JobSearchSiteBackend.Core.Domains.EmploymentOptions.EmploymentOption", null)
                        .WithMany()
                        .HasForeignKey("EmploymentOptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobSearchSiteBackend.Core.Domains.Jobs.Job", null)
                        .WithMany()
                        .HasForeignKey("JobsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobApplicationPersonalFile", b =>
                {
                    b.HasOne("JobSearchSiteBackend.Core.Domains.JobApplications.JobApplication", null)
                        .WithMany()
                        .HasForeignKey("JobApplicationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobSearchSiteBackend.Core.Domains.PersonalFiles.PersonalFile", null)
                        .WithMany()
                        .HasForeignKey("PersonalFilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobJobContractType", b =>
                {
                    b.HasOne("JobSearchSiteBackend.Core.Domains.JobContractTypes.JobContractType", null)
                        .WithMany()
                        .HasForeignKey("JobContractTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobSearchSiteBackend.Core.Domains.Jobs.Job", null)
                        .WithMany()
                        .HasForeignKey("JobsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobLocation", b =>
                {
                    b.HasOne("JobSearchSiteBackend.Core.Domains.Jobs.Job", null)
                        .WithMany()
                        .HasForeignKey("JobsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobSearchSiteBackend.Core.Domains.Locations.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.Companies.Company", b =>
                {
                    b.HasOne("JobSearchSiteBackend.Core.Domains.Countries.Country", "Country")
                        .WithMany("Companies")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.Companies.CompanyAvatar", b =>
                {
                    b.HasOne("JobSearchSiteBackend.Core.Domains.Companies.Company", "Company")
                        .WithMany("CompanyAvatars")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.Companies.CompanyBalanceTransaction", b =>
                {
                    b.HasOne("JobSearchSiteBackend.Core.Domains.Companies.Company", "Company")
                        .WithMany("CompanyBalanceTransactions")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JobSearchSiteBackend.Core.Domains.UserProfiles.UserProfile", "UserProfile")
                        .WithMany("CompanyBalanceTransactions")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Company");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.Companies.CompanyEmployeeInvitation", b =>
                {
                    b.HasOne("JobSearchSiteBackend.Core.Domains.Companies.Company", "Company")
                        .WithMany("CompanyEmployeeInvitations")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JobSearchSiteBackend.Core.Domains.UserProfiles.UserProfile", "InvitedUser")
                        .WithMany("CompanyEmployeeInvitationsReceived")
                        .HasForeignKey("InvitedUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JobSearchSiteBackend.Core.Domains.UserProfiles.UserProfile", "SenderUser")
                        .WithMany("CompanyEmployeeInvitationsSent")
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("InvitedUser");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.CompanyClaims.UserCompanyClaim", b =>
                {
                    b.HasOne("JobSearchSiteBackend.Core.Domains.CompanyClaims.CompanyClaim", "CompanyClaim")
                        .WithMany("UserCompanyClaims")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobSearchSiteBackend.Core.Domains.Companies.Company", "Company")
                        .WithMany("UserCompanyClaims")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobSearchSiteBackend.Core.Domains.UserProfiles.UserProfile", "User")
                        .WithMany("UserCompanyClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("CompanyClaim");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.Countries.CountryCurrency", b =>
                {
                    b.HasOne("JobSearchSiteBackend.Core.Domains.Countries.Country", "Country")
                        .WithMany("CountryCurrencies")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobSearchSiteBackend.Core.Domains.Countries.Currency", "Currency")
                        .WithMany("CountryCurrencies")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.JobApplications.JobApplication", b =>
                {
                    b.HasOne("JobSearchSiteBackend.Core.Domains.Jobs.Job", "Job")
                        .WithMany("JobApplications")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobSearchSiteBackend.Core.Domains.Locations.Location", "Location")
                        .WithMany("JobApplications")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobSearchSiteBackend.Core.Domains.UserProfiles.UserProfile", "User")
                        .WithMany("JobApplications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.JobApplications.JobApplicationTag", b =>
                {
                    b.HasOne("JobSearchSiteBackend.Core.Domains.JobApplications.JobApplication", "JobApplication")
                        .WithMany("Tags")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobApplication");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.JobContractTypes.JobContractType", b =>
                {
                    b.HasOne("JobSearchSiteBackend.Core.Domains.Countries.Country", "Country")
                        .WithMany("JobContractTypes")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.Jobs.Job", b =>
                {
                    b.HasOne("JobSearchSiteBackend.Core.Domains.Categories.Category", "Category")
                        .WithMany("Jobs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobSearchSiteBackend.Core.Domains.Companies.Company", "Company")
                        .WithMany("Jobs")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.Jobs.JobPublicationInterval", b =>
                {
                    b.HasOne("JobSearchSiteBackend.Core.Domains.Countries.CountryCurrency", "CountryCurrency")
                        .WithMany("JobPublicationIntervals")
                        .HasForeignKey("CountryCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CountryCurrency");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.Jobs.JobSalaryInfo", b =>
                {
                    b.HasOne("JobSearchSiteBackend.Core.Domains.Jobs.Job", null)
                        .WithOne("SalaryInfo")
                        .HasForeignKey("JobSearchSiteBackend.Core.Domains.Jobs.JobSalaryInfo", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.Locations.Location", b =>
                {
                    b.HasOne("JobSearchSiteBackend.Core.Domains.Countries.Country", "Country")
                        .WithMany("Locations")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.Locations.LocationRelation", b =>
                {
                    b.HasOne("JobSearchSiteBackend.Core.Domains.Locations.Location", "Ancestor")
                        .WithMany("RelationsWhereThisIsAncestor")
                        .HasForeignKey("AncestorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JobSearchSiteBackend.Core.Domains.Locations.Location", "Descendant")
                        .WithMany("RelationsWhereThisIsDescendant")
                        .HasForeignKey("DescendantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ancestor");

                    b.Navigation("Descendant");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.PersonalFiles.PersonalFile", b =>
                {
                    b.HasOne("JobSearchSiteBackend.Core.Domains.UserProfiles.UserProfile", "User")
                        .WithMany("PersonalFiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.UserProfiles.UserAvatar", b =>
                {
                    b.HasOne("JobSearchSiteBackend.Core.Domains.UserProfiles.UserProfile", "UserProfile")
                        .WithMany("UserAvatars")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.UserProfiles.UserJobApplicationBookmark", b =>
                {
                    b.HasOne("JobSearchSiteBackend.Core.Domains.JobApplications.JobApplication", "JobApplication")
                        .WithMany("UserJobApplicationBookmarks")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobSearchSiteBackend.Core.Domains.UserProfiles.UserProfile", "UserProfile")
                        .WithMany("UserJobApplicationBookmarks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("JobApplication");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.UserProfiles.UserJobBookmark", b =>
                {
                    b.HasOne("JobSearchSiteBackend.Core.Domains.Jobs.Job", "Job")
                        .WithMany("UserJobBookmarks")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobSearchSiteBackend.Core.Domains.UserProfiles.UserProfile", "UserProfile")
                        .WithMany("UserJobBookmarks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.UserProfiles.UserProfile", b =>
                {
                    b.HasOne("JobSearchSiteBackend.Core.Domains.Accounts.MyIdentityUser", "Account")
                        .WithOne("Profile")
                        .HasForeignKey("JobSearchSiteBackend.Core.Domains.UserProfiles.UserProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("JobSearchSiteBackend.Core.Domains.Accounts.MyIdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("JobSearchSiteBackend.Core.Domains.Accounts.MyIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("JobSearchSiteBackend.Core.Domains.Accounts.MyIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("JobSearchSiteBackend.Core.Domains.Accounts.MyIdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobSearchSiteBackend.Core.Domains.Accounts.MyIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("JobSearchSiteBackend.Core.Domains.Accounts.MyIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.Accounts.MyIdentityUser", b =>
                {
                    b.Navigation("Profile");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.Categories.Category", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.Companies.Company", b =>
                {
                    b.Navigation("CompanyAvatars");

                    b.Navigation("CompanyBalanceTransactions");

                    b.Navigation("CompanyEmployeeInvitations");

                    b.Navigation("Jobs");

                    b.Navigation("UserCompanyClaims");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.CompanyClaims.CompanyClaim", b =>
                {
                    b.Navigation("UserCompanyClaims");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.Countries.Country", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("CountryCurrencies");

                    b.Navigation("JobContractTypes");

                    b.Navigation("Locations");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.Countries.CountryCurrency", b =>
                {
                    b.Navigation("JobPublicationIntervals");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.Countries.Currency", b =>
                {
                    b.Navigation("CountryCurrencies");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.JobApplications.JobApplication", b =>
                {
                    b.Navigation("Tags");

                    b.Navigation("UserJobApplicationBookmarks");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.Jobs.Job", b =>
                {
                    b.Navigation("JobApplications");

                    b.Navigation("SalaryInfo");

                    b.Navigation("UserJobBookmarks");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.Locations.Location", b =>
                {
                    b.Navigation("JobApplications");

                    b.Navigation("RelationsWhereThisIsAncestor");

                    b.Navigation("RelationsWhereThisIsDescendant");
                });

            modelBuilder.Entity("JobSearchSiteBackend.Core.Domains.UserProfiles.UserProfile", b =>
                {
                    b.Navigation("CompanyBalanceTransactions");

                    b.Navigation("CompanyEmployeeInvitationsReceived");

                    b.Navigation("CompanyEmployeeInvitationsSent");

                    b.Navigation("JobApplications");

                    b.Navigation("PersonalFiles");

                    b.Navigation("UserAvatars");

                    b.Navigation("UserCompanyClaims");

                    b.Navigation("UserJobApplicationBookmarks");

                    b.Navigation("UserJobBookmarks");
                });
#pragma warning restore 612, 618
        }
    }
}
