<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="AWSSDK.Core" Version="4.0.102.6" />
      <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.101.4" />
      <PackageReference Include="AWSSDK.S3" Version="4.0.103.4" />
      <PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
      <PackageReference Include="Hangfire" Version="1.8.25" />
      <PackageReference Include="Hangfire.SqlServer" Version="1.8.25" />
      <PackageReference Include="MailKit" Version="4.18.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="NEST" Version="7.17.5" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
      <PackageReference Include="NRedisStack" Version="1.8.0" />
      <PackageReference Include="PDFsharp" Version="6.2.4" />
      <PackageReference Include="StackExchange.Redis" Version="3.3.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\JobSearchSiteBackend.Core\JobSearchSiteBackend.Core.csproj" />
	  <ProjectReference Include="..\JobSearchSiteBackend.Shared\JobSearchSiteBackend.Shared.csproj" />
    </ItemGroup>

</Project>
