using JobSearchSiteBackend.Core.Domains.Companies.Dtos;

namespace JobSearchSiteBackend.Core.Domains.Companies.UseCases.SendCompanyEmployeeInvitation;

public record SendCompanyEmployeeInvitationResult(CompanyEmployeeInvitationDto CompanyEmployeeInvitationDto);